### ISSUE TITLE
Can't print private methods that were executed

### ISSUE THREAD

**Issue by royiHamo** [attilapiros/trace-agent#20]
Hello, 
Thank you for the tool it looks very cool and useful!
I'm trying to print all the methods my code executed, I tried with DiagnosticCommand with threadPrint command and also all the other tracing options as trace_with_args and the timing option, but none of them printing the private methods that were executed.
They only print public methods.

Is there a way to print all the methods that are not native and that were executed by the project I'm attaching the agent to?
Inlcuding private and protected methods?
Thank you!

**Comment by attilapiros** [comment]
Hi,

> Thank you for the tool it looks very cool and useful!
Thanks! :)

> They only print public methods.

I am sure it works on private method too as I just used it for something and please take a look these log lines:
```
TraceAgent (trace_args): `private org.apache.hadoop.yarn.api.records.Priority org.apache.spark.deploy.yarn.YarnAllocator.getContainerPriority(int) called with [0]
TraceAgent (trace_args): `private synchronized scala.collection.immutable.Map org.apache.spark.deploy.yarn.YarnAllocator.getPendingAtLocation(java.lang.String) called with [*]
TraceAgent (trace_args): `public scala.collection.immutable.Map org.apache.spark.deploy.yarn.YarnAllocator.getPendingAllocate() called with []
TraceAgent (trace_args): `private scala.collection.mutable.HashMap org.apache.spark.deploy.yarn.YarnAllocator.targetNumExecutorsPerResourceProfileId() called with []
TraceAgent (trace_args): `private scala.collection.mutable.HashMap org.apache.spark.deploy.yarn.YarnAllocator.numExecutorsStartingPerResourceProfileId() called with []
TraceAgent (trace_args): `private synchronized java.util.concurrent.atomic.AtomicInteger org.apache.spark.deploy.yarn.YarnAllocator.getOrUpdateNumExecutorsStartingForRPId(int) call
```

And here is a protected method:
```
TraceAgent (trace_args): `protected void org.apache.hadoop.service.AbstractService.serviceStop() throws java.lang.Exception called with []
```

Could it be your method was inlined?

Best,
Attila

**Comment by attilapiros** [comment]
I am closing this.
